StoreFront.UI.MVC/Controllers/MovieTitlesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StoreFront.DATA.EF;
using System.Drawing;
using StoreFront.UI.MVC.Utilities;
using PagedList;
using PagedList.Mvc;
using StoreFront.UI.MVC.Models;

namespace StoreFront.UI.MVC.Controllers
{
    public class MovieTitlesController : Controller
    {
        private MovieStoreEntities db = new MovieStoreEntities();

        // GET: MovieTitles
        public ActionResult Index(string searchString, int page = 1, int genreid = -1, int catid = -1)
        {
            int pageSize = 6;
            var movies = db.MovieTitles.OrderBy(m => m.MovieTitle1).ToList();

            if (!string.IsNullOrEmpty(searchString))
            {
                movies = movies.Where(m => m.MovieTitle1.ToLower().Contains(searchString.ToLower())).ToList();
            }

            if (genreid != -1)
            {
                movies = movies.Where(m => m.GenreID == genreid).ToList();
            }

            if (catid != -1)
            {
                movies = movies.Where(m => m.CategoryID == catid).ToList();
            }

            ViewBag.SearchString = searchString;

            ViewBag.GenreID = genreid;

            ViewBag.CategoryID = catid;

            return View(movies.ToPagedList(page, pageSize));
        }

        public ActionResult ByPrice(string searchString, int page = 1)
        {
            int pageSize = 6;
            var movies = db.MovieTitles.OrderBy(m => m.Price).ToList();

            if (!string.IsNullOrEmpty(searchString))
            {
                movies = movies.Where(m => m.MovieTitle1.ToLower().Contains(searchString.ToLower())).ToList();
            }

            ViewBag.SearchString = searchString;

            return View(movies.ToPagedList(page, pageSize));
        }

        // GET: MovieTitles/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MovieTitle movieTitle = db.MovieTitles.Find(id);
            if (movieTitle == null)
            {
                return HttpNotFound();
            }
            return View(movieTitle);
        }

        // GET: MovieTitles/Create
        public ActionResult Create()
        {
            ViewBag.AspectRatioID = new SelectList(db.AspectRatios, "AspectRatioID", "AspectRatio1");
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Category1");
            ViewBag.CountryID = new SelectList(db.Countries, "CountryID", "Country1");
            ViewBag.DirectorID = new SelectList(db.Directors, "DirectorID", "FullName");
            ViewBag.GenreID = new SelectList(db.Genres, "GenreID", "GenreName");
            ViewBag.LanguageID = new SelectList(db.Languages, "LanguageID", "Language1");
            ViewBag.MovieRatingID = new SelectList(db.MovieRatings, "MovieRatingID", "MovieRating1");
            ViewBag.StatusID = new SelectList(db.MovieStatus1, "StatusID", "Status");
            return View();
        }

        // POST: MovieTitles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MovieID,MovieTitle1,GenreID,Price,UnitsInStock,ReleaseYear,MovieRatingID,Runtime,DirectorID,CountryID,AspectRatioID,IsColor,LanguageID,Description,Image,StatusID,CategoryID")] MovieTitle movieTitle, HttpPostedFileBase movieImage)
        {
            if (ModelState.IsValid)
            {
                #region File Upload Utility
                string imgName = "noImage.png";

                if (movieImage != null)
                {
                    imgName = movieImage.FileName;

                    string ext = imgName.Substring(imgName.LastIndexOf('.'));
                    string[] goodExts = { ".jpg", ".jpeg", ".gif", ".png" };
                    if (goodExts.Contains(ext.ToLower()) && (movieImage.ContentLength <= 4194304))
                    {
                        imgName = Guid.NewGuid() + ext.ToLower();
                        string savePath = Server.MapPath("~/Content/img/ProductImages/");
                        Image convertedImage = Image.FromStream(movieImage.InputStream);
                        int maxImageSize = 2000;
                        int maxThumbSize = 150;
                        ImageService.ResizeImage(savePath, imgName, convertedImage, maxImageSize, maxThumbSize);
                    }
                    else
                    {
                        imgName = "NoImage.png";
                    }
                }
                #endregion
                movieTitle.Image = imgName;

                db.MovieTitles.Add(movieTitle);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AspectRatioID = new SelectList(db.AspectRatios, "AspectRatioID", "AspectRatio1", movieTitle.AspectRatioID);
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Category1", movieTitle.CategoryID);
            ViewBag.CountryID = new SelectList(db.Countries, "CountryID", "Country1", movieTitle.CountryID);
            ViewBag.DirectorID = new SelectList(db.Directors, "DirectorID", "FirstName", movieTitle.DirectorID);
            ViewBag.GenreID = new SelectList(db.Genres, "GenreID", "GenreName", movieTitle.GenreID);
            ViewBag.LanguageID = new SelectList(db.Languages, "LanguageID", "Language1", movieTitle.LanguageID);
            ViewBag.MovieRatingID = new SelectList(db.MovieRatings, "MovieRatingID", "MovieRating1", movieTitle.MovieRatingID);
            ViewBag.StatusID = new SelectList(db.MovieStatus1, "StatusID", "Status", movieTitle.StatusID);
            return View(movieTitle);
        }

        // GET: MovieTitles/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MovieTitle movieTitle = db.MovieTitles.Find(id);
            if (movieTitle == null)
            {
                return HttpNotFound();
            }
            ViewBag.AspectRatioID = new SelectList(db.AspectRatios, "AspectRatioID", "AspectRatio1", movieTitle.AspectRatioID);
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Category1", movieTitle.CategoryID);
            ViewBag.CountryID = new SelectList(db.Countries, "CountryID", "Country1", movieTitle.CountryID);
            ViewBag.DirectorID = new SelectList(db.Directors, "DirectorID", "FirstName", movieTitle.DirectorID);
            ViewBag.GenreID = new SelectList(db.Genres, "GenreID", "GenreName", movieTitle.GenreID);
            ViewBag.LanguageID = new SelectList(db.Languages, "LanguageID", "Language1", movieTitle.LanguageID);
            ViewBag.MovieRatingID = new SelectList(db.MovieRatings, "MovieRatingID", "MovieRating1", movieTitle.MovieRatingID);
            ViewBag.StatusID = new SelectList(db.MovieStatus1, "StatusID", "Status", movieTitle.StatusID);
            return View(movieTitle);
        }

        // POST: MovieTitles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MovieID,MovieTitle1,GenreID,Price,UnitsInStock,ReleaseYear,MovieRatingID,Runtime,DirectorID,CountryID,AspectRatioID,IsColor,LanguageID,Description,Image,StatusID,CategoryID")] MovieTitle movieTitle, HttpPostedFileBase movieImage)
        {
            if (ModelState.IsValid)
            {
                if (movieImage != null)
                {
                    string imgName = movieImage.FileName;
                    string ext = imgName.Substring(imgName.LastIndexOf('.'));
                    string[] goodExts = { ".jpeg", ".jpg", ".gif", ".png" };
                    if (goodExts.Contains(ext.ToLower()) && (movieImage.ContentLength <= 4194304))
                    {
                        imgName = Guid.NewGuid() + ext.ToLower();
                        string savePath = Server.MapPath("~/Content/img/ProductImages/");
                        Image convertedImage = Image.FromStream(movieImage.InputStream);
                        int maxImageSize = 2000;
                        int maxThumbSize = 150;
                        ImageService.ResizeImage(savePath, imgName, convertedImage, maxImageSize, maxThumbSize);

                        if (movieTitle.Image != null && movieTitle.Image != "NoImage.png")
                        {
                            string path = Server.MapPath("~/Content/img/ProductImages/");
                            ImageService.Delete(path, movieTitle.Image);
                        }

                        movieTitle.Image = imgName;
                    }
                }
                db.Entry(movieTitle).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AspectRatioID = new SelectList(db.AspectRatios, "AspectRatioID", "AspectRatio1", movieTitle.AspectRatioID);
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Category1", movieTitle.CategoryID);
            ViewBag.CountryID = new SelectList(db.Countries, "CountryID", "Country1", movieTitle.CountryID);
            ViewBag.DirectorID = new SelectList(db.Directors, "DirectorID", "FirstName", movieTitle.DirectorID);

StoreFront.UI.MVC/Controllers/ShoppingCartController.cs
using StoreFront.UI.MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StoreFront.DATA.EF;

namespace StoreFront.UI.MVC.Controllers
{
    public class ShoppingCartController : Controller
    {
        // GET: ShoppingCart
        public ActionResult Index()
        {
            var shoppingCart = (Dictionary<int, CartItemViewModel>)Session["cart"];

            if (shoppingCart == null || shoppingCart.Count == 0)
            {
                shoppingCart = new Dictionary<int, CartItemViewModel>();
                ViewBag.Message = "There are no movies in your cart.";
            }
            else
            {
                ViewBag.Message = null;
            }

            return View(shoppingCart);
        }

        public ActionResult UpdateCart(int movieID, int qty)
        {
            if (qty == 0)
            {
                RemoveFromCart(movieID);

                return RedirectToAction("Index");
            }

            Dictionary<int, CartItemViewModel> shoppingCart = (Dictionary<int, CartItemViewModel>)Session["cart"];

            shoppingCart[movieID].Qty = qty;

            Session["cart"] = shoppingCart;

            if (shoppingCart.Count == 0)
            {
                ViewBag.Message = "There are no movies in your cart";
            }

            return RedirectToAction("Index");
        }

        public ActionResult RemoveFromCart(int id)
        {
            Dictionary<int, CartItemViewModel> shoppingCart = (Dictionary<int, CartItemViewModel>)Session["cart"];

            shoppingCart.Remove(id);

            if (shoppingCart.Count == 0)
            {
                Session["cart"] = null;
            }

            return RedirectToAction("Index");
        }
    }
}

StoreFront.UI.MVC/Views/ShoppingCart/Index.cshtml
@*@model IEnumerable<StoreFront.UI.MVC.Models.CartItemViewModel>*@
@model Dictionary<int, StoreFront.UI.MVC.Models.CartItemViewModel>
@{
    ViewBag.Title = "Shopping Cart";
    decimal? cartTotal = 0;
    int totalCountOfItems = 0;
}
<div id="all">
    <div id="content">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <!-- breadcrumb-->
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">Home</a></li>
                            <li aria-current="page" class="breadcrumb-item"><a href="@Url.Action("Index", "MovieTitles")">Shop</a></li>
                            <li aria-current="page" class="breadcrumb-item active">Shopping Cart</li>
                        </ol>
                    </nav>
                </div>
                <div id="basket" class="col-lg-9">
                    <div class="box">
                        <h1>Shopping cart</h1>
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th colspan="2">Product</th>
                                        <th class="update">Quantity</th>
                                        <th>Unit price</th>
                                        <th colspan="2">Total</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td><a href="@Url.Action("Details", "MovieTitles", new { id = item.Value.Product.MovieID })"><img src="~/Content/img/ProductImages/t_@item.Value.Product.Image" alt="@item.Value.Product.MovieTitle1 Image"></a></td>
                                            <td style="font-size: 0.9em;"><a href="@Url.Action("Details", "MovieTitles", new { id = item.Value.Product.MovieID })">@item.Value.Product.MovieTitle1</a></td>

                                            <td class="update">
                                                @using (Html.BeginForm("UpdateCart", "ShoppingCart", FormMethod.Post))
                                                {
                                                    @Html.Hidden("movieID", item.Value.Product.MovieID)
                                                    @Html.TextBox("qty", item.Value.Qty, new { @class = "form-control", style = "max-width: 80px;display:inline-block; " })
                                                    <input type="submit" value="Update" class="btn btn-primary update" style="max-width:150px;" />
                                                }
                                            </td>
                                            @{totalCountOfItems += item.Value.Qty;}
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Value.Product.Price)
                                            </td>
                                            <td>
                                                @{
                                                    decimal? lineTotal = item.Value.Product.Price * item.Value.Qty;
                                                    cartTotal += lineTotal;
                                                }
                                                @string.Format($"{lineTotal:c}")
                                            </td>
                                            <td><i class="fa fa-trash-o"> @Html.ActionLink("Remove", "RemoveFromCart", new { id = item.Value.Product.MovieID })<br /></i></td>
                                        </tr>
                                    }
                            </table>
                        </div>
                        <!-- /.table-responsive-->
                        <div class="box-footer d-flex justify-content-between flex-column flex-lg-row">
                            <div class="left"><a href="@Url.Action("Index", "MovieTitles")" class="btn btn-outline-secondary"><i class="fa fa-chevron-left"></i> Continue shopping</a></div>
                            <div class="right">
                                <button type="submit" class="btn btn-primary">Proceed to checkout <i class="fa fa-chevron-right"></i></button>
                            </div>
                        </div>
                    </div>
                    <!-- /.box-->
                </div>
                <!-- /.col-lg-9-->
                <div class="col-lg-3">
                    <div id="order-summary" class="box">
                        <div class="box-header">
                            <h3 class="mb-0">Order summary</h3>
                        </div>
                        @*<p class="text-muted">Shipping and additional costs are calculated based on the values you have entered.</p>*@
                        <div class="table-responsive">
                            <table class="table">
                                <tbody>
                                    @*<tr>
                                            <td>Order subtotal</td>
                                            <th>@string.Format($"{cartTotal:c}")</th>
                                        </tr>*@
                                    @*<tr>
                                            <td>Shipping and handling</td>
                                            <th>$10.00</th>
                                        </tr>*@
                                    <tr>
                                        <td>Qty</td>
                                        <th>@totalCountOfItems @(totalCountOfItems > 1 || totalCountOfItems == 0 ? "movies" : "movie")</th>
                                    </tr>
                                    <tr class="total">
                                        <td>Total</td>
                                        <th>@string.Format($"{cartTotal:c}")</th>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <!-- /.col-md-3-->
            </div>
        </div>
    </div>
</div>