StoreFront.UI.MVC/Controllers/ActorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StoreFront.DATA.EF;

namespace StoreFront.UI.MVC.Controllers
{
    public class ActorsController : Controller
    {
        private MovieStoreEntities db = new MovieStoreEntities();

        // GET: Actors
        public ActionResult Index()
        {
            return View(db.Actors.ToList());
        }

        // GET: Actors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Actor actor = db.Actors.Find(id);
            if (actor == null)
            {
                return HttpNotFound();
            }
            return View(actor);
        }

        // GET: Actors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Actors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ActorID,FirstName,LastName")] Actor actor)
        {
            if (ModelState.IsValid)
            {
                db.Actors.Add(actor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(actor);
        }

        // GET: Actors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Actor actor = db.Actors.Find(id);
            if (actor == null)
            {
                return HttpNotFound();
            }
            return View(actor);
        }

        // POST: Actors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ActorID,FirstName,LastName")] Actor actor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(actor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(actor);
        }

        // GET: Actors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Actor actor = db.Actors.Find(id);
            if (actor == null)
            {
                return HttpNotFound();
            }
            return View(actor);
        }

        // POST: Actors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Actor actor = db.Actors.Find(id);
            db.Actors.Remove(actor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StoreFront.UI.MVC/Controllers/DirectorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StoreFront.DATA.EF;
using PagedList;
using PagedList.Mvc;

namespace StoreFront.UI.MVC.Controllers
{
    public class DirectorsController : Controller
    {
        private MovieStoreEntities db = new MovieStoreEntities();

        #region Ajax Operations

        //Any unused (replaced by ajax) actions below should be commented out or deleted entirely as they still will route to the old views. This can only be achieved by URL hacking (someone would have to go into url and enter publisher/edit etc. etc. to get to it). AKA make sure unused views aren't accessible

        #region Ajax Delete
        [AcceptVerbs(HttpVerbs.Post)]
        public JsonResult AjaxDelete(int id)
        {
            //get the publisher from the database
            Director dir = db.Directors.Find(id);

            //remove the publisher from EF
            db.Directors.Remove(dir);

            //save the changes to the database
            db.SaveChanges();

            //create a message to send to the user as a JSON result
            var message = $"Deleted the following publisher from the database: {dir.FullName}";

            //return the jsonResult
            return Json(new
            {
                id = id,
                message = message

            });
        }

        #endregion

        #region AJAX Details
        [HttpGet]
        public PartialViewResult DirectorDetails(int id)
        {
            //retrieve the publisher by id
            Director dir = db.Directors.Find(id);

            //return the partial view WITH the publisher object
            return PartialView(dir);

            //for this view:
            //right click and add aprtial view
            //scaffold to details
            //Publisher - model
            //CHECK the PartialView Checkbox
        }
        #endregion

        #region AJAX Create
        //Add the publisher to the db via AJAX and return a result
        public JsonResult AjaxCreate(Director director)
        {
            //even though this is a json result, the VIEW is a partial view so that we can render it in the index (our div that we created)

            //hard code that each publisher will be active by default (no checkbox in the form)
            //any pub created using this ajax method will be set to IsActive = true;

            db.Directors.Add(director);
            db.SaveChanges();
            return Json(director);
        }

        #endregion

        #region AJAX Edit [GET]
        public PartialViewResult DirectorEdit(int id)
        {
            //retrieve the publisher and retrun to the view with data
            //populated for updates
            Director director = db.Directors.Find(id);
            return PartialView(director);
        }

        #endregion

        #region AJAX Edit [POST]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult AjaxEdit(Director director)
        {
            db.Entry(director).State = EntityState.Modified;//telling it we're modifying rather than adding a new one
            db.SaveChanges();
            return Json(director);//what we use to translate to create our brand new role translated by data, and is what will overlay our new table row
        }
        #endregion

        #endregion

        public ActionResult Tiles()
        {
            return View(db.Directors.ToList());
        }

        // GET: Directors
        public ActionResult Index(string searchString, int page = 1)
        {
            int pageSize = 10;
            var dirs = db.Directors.OrderBy(m => m.LastName).ToList();

            if (!string.IsNullOrEmpty(searchString))
            {
                dirs = dirs.Where(m => m.FullName.ToLower().Contains(searchString.ToLower())).ToList();
            }

            ViewBag.SearchString = searchString;

            return View(dirs.ToPagedList(page, pageSize));
        }

        // GET: Directors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Director director = db.Directors.Find(id);
            if (director == null)
            {
                return HttpNotFound();
            }
            return View(director);
        }

        // GET: Directors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Directors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DirectorID,FirstName,LastName")] Director director)
        {
            if (ModelState.IsValid)
            {
                db.Directors.Add(director);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(director);
        }

        // GET: Directors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Director director = db.Directors.Find(id);
            if (director == null)
            {
                return HttpNotFound();
            }
            return View(director);
        }

        // POST: Directors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DirectorID,FirstName,LastName")] Director director)
        {
            if (ModelState.IsValid)
            {
                db.Entry(director).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(director);
        }

        // GET: Directors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Director director = db.Directors.Find(id);
            if (director == null)
            {
                return HttpNotFound();
            }
            return View(director);
        }

        // POST: Directors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Director director = db.Directors.Find(id);
            db.Directors.Remove(director);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StoreFront.UI.MVC/Controllers/RolesAdminController.cs
using StoreFront.UI.MVC.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Collections.Generic;

namespace StoreFront.UI.MVC.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RolesAdminController : Controller
    {
        public RolesAdminController()
        {
        }

        public RolesAdminController(ApplicationUserManager userManager,
            ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            set
            {
                _userManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        //
        // GET: /Roles/
        [HttpGet]
        public ActionResult Index()
        {
            return View(RoleManager.Roles);
        }

        //
        // GET: /Roles/Details/5
        [HttpGet]
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = await RoleManager.FindByIdAsync(id);
            // Get the list of Users in this Role
            var users = new List<ApplicationUser>();

            // Get the list of Users in this Role
            foreach (var user in UserManager.Users.ToList())
            {
                if (await UserManager.IsInRoleAsync(user.Id, role.Name))
                {
                    users.Add(user);
                }
            }

            ViewBag.Users = users;
            ViewBag.UserCount = users.Count();
            return View(role);
        }

        //
        // GET: /Roles/Create
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Roles/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(RoleViewModel roleViewModel)
        {
            if (ModelState.IsValid)
            {
                var role = new IdentityRole(roleViewModel.Name);
                var roleresult = await RoleManager.CreateAsync(role);
                if (!roleresult.Succeeded)
                {
                    ModelState.AddModelError("", roleresult.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }

        //
        // GET: /Roles/Edit/Admin
        [HttpGet]
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = await RoleManager.FindByIdAsync(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            RoleViewModel roleModel = new RoleViewModel { Id = role.Id, Name = role.Name };
            return View(roleModel);
        }

        //
        // POST: /Roles/Edit/5
        [HttpPost]

        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Name,Id")] RoleViewModel roleModel)
        {
            if (ModelState.IsValid)
            {
                var role = await RoleManager.FindByIdAsync(roleModel.Id);
                role.Name = roleModel.Name;
                await RoleManager.UpdateAsync(role);
                return RedirectToAction("Index");
            }
            return View();
        }

        //
        // GET: /Roles/Delete/5
        [HttpGet]
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = await RoleManager.FindByIdAsync(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            return View(role);
        }

        //
        // POST: /Roles/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id, string deleteUser)
        {
            if (ModelState.IsValid)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                var role = await RoleManager.FindByIdAsync(id);
                if (role == null)
                {
                    return HttpNotFound();
                }
                IdentityResult result;
                if (deleteUser != null)
                {
                    result = await RoleManager.DeleteAsync(role);
                }
                else
                {
                    result = await RoleManager.DeleteAsync(role);
                }
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

StoreFront.UI.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewBag.Title</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    @Styles.Render("~/bundles/css")
    <!--jQueryUI STYLE-->
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" />
    <!-- Google fonts - Roboto -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,700">
    <!-- Favicon-->
    <link rel="shortcut icon" href="~/favicon.ico">
    <!-- Tweaks for older IEs-->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
</head>
<body>
    <!-- navbar-->
    <header class="header mb-5">
        <!--
        *** TOPBAR ***
        _________________________________________________________
        -->
        <div id="top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 offer mb-3 mb-lg-0"></div>
                    <div class="col-lg-6 text-center text-lg-right">
                        <ul class="menu list-inline mb-0">
                            @Html.Partial("_LoginPartial")
                            <li class="list-inline-item"><a href="@Url.Action("Contact", "Home")">Contact</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- *** TOP BAR END ***-->
        </div>

        <nav class="navbar navbar-expand-lg">
            <div class="container">
                <a href="@Url.Action("Index", "Home")" class="navbar-brand home"><img src="~/Content/img/4ko Logo.png" alt="4KO logo" class="d-none d-md-inline-block"><img src="~/Content/img/4ko Logo.png" alt="4KO logo" class="d-inline-block d-md-none"><span class="sr-only">4KO - Go to Home</span></a>
                <div class="navbar-buttons">
                    <button type="button" data-toggle="collapse" data-target="#navigation" class="btn btn-outline-secondary navbar-toggler"><span class="sr-only">Toggle navigation</span><i class="fa fa-align-justify"></i></button>
                    <button type="button" data-toggle="collapse" data-target="#search" class="btn btn-outline-secondary navbar-toggler"><span class="sr-only">Toggle search</span><i class="fa fa-search"></i></button><a href="@Url.Action("Index", "ShoppingCart")" class="btn btn-outline-secondary navbar-toggler"><i class="fa fa-shopping-cart"></i></a>
                </div>
                <div id="navigation" class="collapse navbar-collapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a href="@Url.Action("Index", "Home")" class="nav-link class=@if (ViewBag.Title == "4KO")
                            {
                            @Html.Encode(Html.Raw("<html> active </html>"));
                            }
                        ">Home</a>
                        </li>
                        <li id="shopNav" class="nav-item dropdown menu-large">
                            <a href="@Url.Action("Index", "MovieTitles")" class="nav-link class=@if (ViewBag.Title == "Shop")
                            {
                            @Html.Encode(Html.Raw("<html> active </html>"));
                            }
                        ">Shop</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li id="shopNav" class="nav-item dropdown menu-large">
                                <a href="#" data-toggle="dropdown" data-hover="dropdown" data-delay="200" class="dropdown-toggle nav-link @if (ViewBag.Title != "4KO" && ViewBag.Title != "Shop" && ViewBag.Title != "Account" && ViewBag.Title != "Details" && ViewBag.Title != "Contact")
                                {
                            @Html.Encode(Html.Raw("<html> active </html>"));
                                }
                        ">Manage<b class="caret"></b></a>
                                <ul class="dropdown-menu megamenu">
                                    <li>
                                        <div class="row">
                                            <div class="col-md-6 col-lg-3">
                                                <h5>Actor</h5>
                                                <ul class="list-unstyled mb-3">
                                                    <li class="nav-item"><a href="@Url.Action("Index", "Actors")" class="nav-link">See Actors Index</a></li>
                                                    <li class="nav-item"><a href="@Url.Action("Create", "Actors")" class="nav-link">Create</a></li>
                                                </ul>
                                            </div>
                                            <div class="col-md-6 col-lg-3">
                                                <h5>Director</h5>
                                                <ul class="list-unstyled mb-3">
                                                    <li class="nav-item"><a href="@Url.Action("Index", "Directors")" class="nav-link">See Director Index</a></li>
                                                    <li class="nav-item"><a href="@Url.Action("Create", "Directors")" class="nav-link">Create</a></li>
                                                </ul>
                                            </div>
                                            <div class="col-md-6 col-lg-3">
                                                <h5>Movies</h5>
                                                <ul class="list-unstyled mb-3">
                                                    <li class="nav-item"><a href="@Url.Action("Create", "MovieTitles")" class="nav-link">Create</a></li>
                                                    <li class="nav-item"><a href="@Url.Action("Index", "MovieTitles")" class="nav-link">See Movies Index</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </li>
                        }
                    </ul>
                    <div class="navbar-buttons d-flex justify-content-end">
                        <!-- /.nav-collapse-->
                        @if (ViewBag.Title == "Shop")
                        {
                            <div id="search-not-mobile" class="navbar-collapse collapse"></div><a data-toggle="collapse" href="#search" class="btn navbar-btn btn-primary d-none d-lg-inline-block"><span class="sr-only">Toggle search</span><i class="fa fa-search"></i></a>
                        }
                        @if (Session["cart"] != null)
                        {
                            <div>
                                @{
                                    Dictionary<int, StoreFront.UI.MVC.Models.CartItemViewModel> prods = (Dictionary<int, StoreFront.UI.MVC.Models.CartItemViewModel>)Session["cart"];
                                    var prodCount = prods.Sum(p => p.Value.Qty);
                                }
                                <a href="@Url.Action("Index", "ShoppingCart")" class="btn btn-primary navbar-btn">
                                    <i class="fa fa-shopping-cart fa-lg"></i>
                                    <sup>@prodCount  @(prodCount > 1 || prodCount == 0 ? "movies" : "movie") in cart</sup>
                                </a>
                            </div>
                        }
                        else
                        {
                            <div>
                                <a href="@Url.Action("Index", "ShoppingCart")" class="btn btn-primary navbar-btn">
                                    <i class="fa fa-shopping-cart fa-lg"></i>
                                    <sup>Empty</sup>
                                </a>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </nav>
        <div id="search" class="collapse">
            <div class="container">
                @if (ViewBag.Title == "Shop")
                {
                    <form role="search" class="ml-auto">
                        <div class="input-group">
                            <div class="col-md-6">
                                @Html.TextBox("SearchString", ViewBag.SearchString as string, new { @placeholder = "Search by Title", @class = "form-control" })
                            </div>
                            <div class="col-md-2 text-center">
                                <input type="submit" value="See Results" class="btn btn-primary" />
                            </div>
                            <div class="col-md-1"></div>
                            <div class="col-md-2">
                                @Html.ActionLink("Reset", "Index", "MovieTitles", null, new { @class = "btn" })
                            </div>
                        </div>
                    </form>
                }
            </div>
        </div>
    </header>
    <div id="MessageDisplay" class="text-center">
        <div class="col-md-12 col-md-offset-1" id="MessageContent"></div>
    </div>
    @RenderBody()
    <!--
    *** FOOTER ***
    _________________________________________________________
    -->
    <div id="footer">
        <div class="container">
            <div class="row text-center">
                @if (User.IsInRole("Admin"))
                {
                    <div class="col-lg-2 col-md-4">
                        <h4 class="mb-3">Admin section</h4>
                        <ul class="list-unstyled">
                            <li><a href="@Url.Action("Index", "UsersAdmin")">Manage Users</a></li>
                            <li><a href="@Url.Action("Index", "RolesAdmin")">Manage Roles</a></li>
                        </ul>
                    </div>
                }
                <div class="col-lg-2 col-md-4">
                    <h4 class="mb-3">User section</h4>
                    <ul class="list-unstyled">
                        @Html.Partial("_LoginPartial")
                    </ul>
                </div>
                <div class="col-lg-2 col-md-4 text-center">
                    <h4 class="mb-3">Pages</h4>
                    <ul class="list-unstyled">
                        <li><a href="@Url.Action("Contact", "Home")">Contact us</a></li>
                    </ul>
                </div>
            </div>
            <!-- /.row-->
        </div>
        <!-- /.container-->
    </div>
    <!-- /#footer-->
    <!-- *** FOOTER END ***-->
    <!--
    *** COPYRIGHT ***
    _________________________________________________________
    -->
    <div id="copyright">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 mb-2 mb-lg-0">
                    <p class="text-center text-lg-left">©@DateTime.Now David Muolo.</p>
                </div>
                <div class="col-lg-6">
                    <p class="text-center text-lg-right">
                        Template design by <a href="https://bootstrapious.com/">Bootstrapious</a>
                        <!-- If you want to remove this backlink, pls purchase an Attribution-free License at https://bootstrapious.com/p/obaju-e-commerce-template. Big thanks!-->
                    </p>
                </div>
            </div>
        </div>
    </div>
    <!-- *** COPYRIGHT END ***-->
    <!-- JavaScript files-->
    @Scripts.Render("~/bundles/js")
    <!--jQueryUI script-->
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <!--Ajax Script-->
    <script src="https://cdn.jsdelivr.net/jquery.ajax.unobtrusive/3.2.4/jquery.unobtrusive-ajax.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

StoreFront.UI.MVC/Views/Shared/_OriginalLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                    @if (Request.IsAuthenticated && User.IsInRole("Admin")) {
                        <li>@Html.ActionLink("RolesAdmin", "Index", "RolesAdmin")</li>
                        <li>@Html.ActionLink("UsersAdmin", "Index", "UsersAdmin")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>