StoreFront.UI.MVC/Controllers/UserAdminController.cs
using StoreFront.UI.MVC.Models;
using Microsoft.AspNet.Identity.Owin;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace StoreFront.UI.MVC.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersAdminController : Controller
    {
        public UsersAdminController()
        {
        }

        public UsersAdminController(ApplicationUserManager userManager, ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        //
        // GET: /Users/
        [HttpGet]
        public async Task<ActionResult> Index()
        {
            return View(await UserManager.Users.ToListAsync());
        }

        //
        // GET: /Users/Details/5
        [HttpGet]
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);

            ViewBag.RoleNames = await UserManager.GetRolesAsync(user.Id);

            return View(user);
        }

        //
        // GET: /Users/Create
        [HttpGet]
        public async Task<ActionResult> Create()
        {
            //Get the list of Roles
            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
            return View();
        }

        //
        // POST: /Users/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(RegisterViewModel userViewModel, params string[] selectedRoles)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { UserName = userViewModel.Email, Email = userViewModel.Email };
                var adminresult = await UserManager.CreateAsync(user, userViewModel.Password);

                //Add User to the selected Roles 
                if (adminresult.Succeeded)
                {
                    if (selectedRoles != null)
                    {
                        var result = await UserManager.AddToRolesAsync(user.Id, selectedRoles);
                        if (!result.Succeeded)
                        {
                            ModelState.AddModelError("", result.Errors.First());
                            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
                            return View();
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError("", adminresult.Errors.First());
                    ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
                    return View();

                }
                return RedirectToAction("Index");
            }
            ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
            return View();
        }

        //
        // GET: /Users/Edit/1
        [HttpGet]
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            var userRoles = await UserManager.GetRolesAsync(user.Id);

            return View(new EditUserViewModel()
            {
                Id = user.Id,
                Email = user.Email,
                RolesList = RoleManager.Roles.ToList().Select(x => new SelectListItem()
                {
                    Selected = userRoles.Contains(x.Name),
                    Text = x.Name,
                    Value = x.Name
                })
            });
        }

        //
        // POST: /Users/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Email,Id")] EditUserViewModel editUser, params string[] selectedRole)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindByIdAsync(editUser.Id);
                if (user == null)
                {
                    return HttpNotFound();
                }

                user.UserName = editUser.Email;
                user.Email = editUser.Email;

                var userRoles = await UserManager.GetRolesAsync(user.Id);

                selectedRole = selectedRole ?? new string[] { };

                var result = await UserManager.AddToRolesAsync(user.Id, selectedRole.Except(userRoles).ToArray<string>());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                result = await UserManager.RemoveFromRolesAsync(user.Id, userRoles.Except(selectedRole).ToArray<string>());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Something failed.");
            return View();
        }

        //
        // GET: /Users/Delete/5
        [HttpGet]
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        //
        // POST: /Users/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            if (ModelState.IsValid)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                var user = await UserManager.FindByIdAsync(id);
                if (user == null)
                {
                    return HttpNotFound();
                }
                var result = await UserManager.DeleteAsync(user);
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

StoreFront.UI.MVC/Views/UsersAdmin/Create.cshtml
@model StoreFront.UI.MVC.Models.RegisterViewModel
@{
    ViewBag.Title = "Create User";
}
<div id="all">
    <div id="content">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <!-- breadcrumb-->
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">Home</a></li>
                            <li aria-current="page" class="breadcrumb-item">@ViewBag.Title</li>
                        </ol>
                    </nav>
                </div>
                <div id="blog-post" class="col-lg-9">
                    <div class="box">
                        <h1>@ViewBag.Title</h1>
                        <div id="post-content">
                            @using (Html.BeginForm("Create", "UsersAdmin", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                            {
                                @Html.AntiForgeryToken()
                                @Html.ValidationSummary("", new { @class = "text-error" })
                                <div class="form-group">
                                    @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
                                    <div class="col-md-10">
                                        @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
                                    <div class="col-md-10">
                                        @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-6 control-label" })
                                    <div class="col-md-10">
                                        @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-6 control-label">
                                        Select User Role
                                    </label>
                                    <div class="col-md-10">
                                        @foreach (var item in (SelectList)ViewBag.RoleId)
                                        {
                                            <input type="checkbox" name="SelectedRoles" value="@item.Value" class="checkbox-inline" />
                                            @Html.Label(item.Value, new { @class = "control-label" })
                                        }
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="submit" class="btn btn-primary" value="Create" />
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                    <!-- /.box-->
                </div>
                <!-- /#blog-post-->
                <div class="col-lg-3">
                    <!--
                    *** BLOG MENU ***
                    _________________________________________________________
                    -->
                    <div class="card sidebar-menu mb-4">
                        <div class="card-header">
                            <h3 class="h4 panel-title">Manage Users</h3>
                        </div>
                        <div class="card-body">
                            <ul class="nav flex-column nav-pills">
                                <li>
                                    <a href="@Url.Action("Index", "UsersAdmin")" class="nav-link">Back to Users</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- /.col-lg-3-->
                    <!-- *** BLOG MENU END ***-->
                    <div class="banner"><img src="~/Content/img/SliderBanner.png" alt="Logo Banner" class="img-fluid bannerPhoto"></div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StoreFront.UI.MVC/Views/UsersAdmin/Delete.cshtml
@model StoreFront.UI.MVC.Models.ApplicationUser
@{
    ViewBag.Title = "Delete User";
}
<div id="all">
    <div id="content">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <!-- breadcrumb-->
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">Home</a></li>
                            <li aria-current="page" class="breadcrumb-item">@ViewBag.Title</li>
                        </ol>
                    </nav>
                </div>
                <div id="blog-post" class="col-lg-9">
                    <div class="box text-center">
                        <h3 style="color: red;">Are you sure you want to delete "@Model.Email" from Users?</h3>
                        <hr />
                        <div id="post-content text-center">
                            <div>
                                <dl class="dl-horizontal text-center">
                                    <dt>
                                        @Html.DisplayNameFor(model => model.UserName)
                                    </dt>
                                    <dd>
                                        @Html.DisplayFor(model => model.UserName)
                                    </dd>
                                </dl>
                                @using (Html.BeginForm())
                                {
                                    @Html.AntiForgeryToken()

                                    <div class="form-actions no-color text-center">
                                        <input type="submit" value="Delete" class="btn btn-danger" />
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                    <!-- /.box-->
                </div>
                <!-- /#blog-post-->
                <div class="col-lg-3">
                    <!--
                    *** BLOG MENU ***
                    _________________________________________________________
                    -->
                    <div class="card sidebar-menu mb-4">
                        <div class="card-header">
                            <h3 class="h4 panel-title">Manage Users</h3>
                        </div>
                        <div class="card-body">
                            <ul class="nav flex-column nav-pills">
                                <li>
                                    <a href="@Url.Action("Create", "UsersAdmin")" class="nav-link">Create</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Index", "UsersAdmin")" class="nav-link">Back to Users</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- /.col-lg-3-->
                    <!-- *** BLOG MENU END ***-->
                    <div class="banner"><img src="~/Content/img/SliderBanner.png" alt="Logo Banner" class="img-fluid bannerPhoto"></div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StoreFront.UI.MVC/Views/UsersAdmin/Details.cshtml
@model StoreFront.UI.MVC.Models.ApplicationUser
@{
    ViewBag.Title = "User Details";
}

<div id="all">
    <div id="content">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <!-- breadcrumb-->
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">Home</a></li>
                            <li aria-current="page" class="breadcrumb-item">@ViewBag.Title</li>
                        </ol>
                    </nav>
                </div>
                <div id="blog-post" class="col-lg-9">
                    <div class="box text-center">
                        <h1>@ViewBag.Title</h1>
                        <hr />
                        <div id="post-content text-center">
                            <div>
                                <h4>List of roles for user @Model.Email:</h4>
                                @if (ViewBag.RoleNames.Count == 0)
                                {
                                    <hr />
                                    <p>No roles found for this user.</p>
                                }
                                <table class="table">
                                    @foreach (var item in ViewBag.RoleNames)
                                    {
                                        <tr>
                                            <td>
                                                @item
                                            </td>
                                        </tr>
                                    }
                                </table>
                            </div>
                            <p>
                                @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "btn btn-success" })
                            </p>
                        </div>
                    </div>
                    <!-- /.box-->
                </div>
                <!-- /#blog-post-->
                <div class="col-lg-3">
                    <!--
                    *** BLOG MENU ***
                    _________________________________________________________
                    -->
                    <div class="card sidebar-menu mb-4">
                        <div class="card-header">
                            <h3 class="h4 panel-title">Manage Users</h3>
                        </div>
                        <div class="card-body">
                            <ul class="nav flex-column nav-pills">
                                <li>
                                    <a href="@Url.Action("Create", "UsersAdmin")" class="nav-link">Create</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Index", "UsersAdmin")" class="nav-link">Back to Users</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- /.col-lg-3-->
                    <!-- *** BLOG MENU END ***-->
                    <div class="banner"><img src="~/Content/img/SliderBanner.png" alt="Logo Banner" class="img-fluid bannerPhoto"></div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StoreFront.UI.MVC/Views/UsersAdmin/Edit.cshtml
@model StoreFront.UI.MVC.Models.EditUserViewModel
@{
    ViewBag.Title = "Edit User";
}
<div id="all">
    <div id="content">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <!-- breadcrumb-->
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">Home</a></li>
                            <li aria-current="page" class="breadcrumb-item">@ViewBag.Title</li>
                        </ol>
                    </nav>
                </div>
                <div id="blog-post" class="col-lg-9 text-center">
                    <div class="box text-center">
                        <h1>@ViewBag.Title</h1>
                        <div class="text-center" id="post-content">
                            @using (Html.BeginForm())
                            {
                                @Html.AntiForgeryToken()

                                <div class="form-horizontal">
                                    <hr />
                                    @Html.ValidationSummary(true)
                                    @Html.HiddenFor(model => model.Id)
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
                                        <div class="col-md-12 text-center">
                                            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.Email)
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <span class=" col-md-12">
                                            @foreach (var item in Model.RolesList)
                                            {
                                                <input type="checkbox" name="SelectedRole" value="@item.Value" checked="@item.Selected" class="checkbox-inline" />
                                                @Html.Label(item.Value, new { @class = "control-label" })
                                            }
                                        </span>
                                    </div>
                                    <div class="form-group">
                                        <div class="col-md-offset-2 col-md-12">
                                            <input type="submit" value="Save" class="btn btn-success" />
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                    <!-- /.box-->
                </div>
                <!-- /#blog-post-->
                <div class="col-lg-3">
                    <!--
                    *** BLOG MENU ***
                    _________________________________________________________
                    -->
                    <div class="card sidebar-menu mb-4">
                        <div class="card-header">
                            <h3 class="h4 panel-title">Manage Users</h3>
                        </div>
                        <div class="card-body">
                            <ul class="nav flex-column nav-pills">
                                @if (User.IsInRole("Admin"))
                                {
                                    <li>
                                        <a href="@Url.Action("Create", "UsersAdmin")" class="nav-link class=@if (ViewBag.Title == "Create Director")
                                        {
                            @Html.Encode(Html.Raw("<html> active </html>"));
                                        }">Create</a>
                                    </li>
                                }
                                <li>
                                    <a href="@Url.Action("Index", "UsersAdmin")" class="nav-link">Back to Users</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- /.col-lg-3-->
                    <!-- *** BLOG MENU END ***-->
                    <div class="banner"><img src="~/Content/img/SliderBanner.png" alt="Logo Banner" class="img-fluid bannerPhoto"></div>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StoreFront.UI.MVC/Views/UsersAdmin/Index.cshtml
@model IEnumerable<StoreFront.UI.MVC.Models.ApplicationUser>
@{
    ViewBag.Title = "Users Index";
}
<div id="all">
    <div id="content">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <!-- breadcrumb-->
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">Home</a></li>
                            <li aria-current="page" class="breadcrumb-item">@ViewBag.Title</li>
                        </ol>
                    </nav>
                </div>
                <div id="blog-post" class="col-lg-9 text-center">
                    <div class="box text-center">
                        <h1>@ViewBag.Title</h1>
                        <br />
                        <div class="text-center" id="post-content">
                            <table class="table">
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.UserName)
                                    </th>
                                    <th>
                                    </th>
                                </tr>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.UserName)
                                        </td>
                                        <td>
                                            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                                            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                                            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                                        </td>
                                    </tr>
                                }
                            </table>
                        </div>
                    </div>
                    <!-- /.box-->
                </div>
                <!-- /#blog-post-->
                <div class="col-lg-3">
                    <!--
                    *** BLOG MENU ***
                    _________________________________________________________
                    -->
                    <div class="card sidebar-menu mb-4">
                        <div class="card-header">
                            <h3 class="h4 panel-title">Manage Users</h3>
                        </div>
                            <div class="card-body">
                                <ul class="nav flex-column nav-pills">
                                    <li>
                                        <a href="@Url.Action("Create", "UsersAdmin")" class="nav-link class=@if (ViewBag.Title == "Create User")
                            {
                            @Html.Encode(Html.Raw("<html> active </html>"));
                                        }">Create</a>
                                    </li>
                                </ul>
                            </div>
                    </div>
                    <!-- /.col-lg-3-->
                    <!-- *** BLOG MENU END ***-->
                    <div class="banner"><img src="~/Content/img/SliderBanner.png" alt="Logo Banner" class="img-fluid bannerPhoto"></div>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}